Laravel-proyect/laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');


Route::resource('users', 'UserController');


Route::resource('personas', 'PersonaController');

Route::resource('rols', 'RolController');

Route::resource('ciudads', 'CiudadController');

Route::resource('vehiculos', 'VehiculoController');

Route::resource('personaPorVehiculos', 'Persona_por_VehiculoController');

Route::resource('marcas', 'MarcaController');

Laravel-proyect/laravel/app/Models/Persona_por_Vehiculo.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Persona_por_Vehiculo",
 *      required={"vehiculos_id", "personas_id", "created_at"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="vehiculos_id",
 *          description="vehiculos_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="personas_id",
 *          description="personas_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Persona_por_Vehiculo extends Model
{
    use SoftDeletes;

    public $table = 'persona_por_vehiculo';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'vehiculos_id',
        'personas_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'vehiculos_id' => 'integer',
        'personas_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'vehiculos_id' => 'required',
        'personas_id' => 'required',
        'created_at' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function personas()
    {
        return $this->belongsTo(\App\Models\Persona::class, 'personas_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function vehiculos()
    {
        return $this->belongsTo(\App\Models\Vehiculo::class, 'vehiculos_id');
    }
}

Laravel-proyect/laravel/app/Http/Controllers/Persona_por_VehiculoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\Persona_por_VehiculoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreatePersona_por_VehiculoRequest;
use App\Http\Requests\UpdatePersona_por_VehiculoRequest;
use App\Repositories\Persona_por_VehiculoRepository;
use App\Http\Controllers\AppBaseController;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Response;

class Persona_por_VehiculoController extends AppBaseController
{
    /** @var  Persona_por_VehiculoRepository */
    private $personaPorVehiculoRepository;

    public function __construct(Persona_por_VehiculoRepository $personaPorVehiculoRepo)
    {
        $this->personaPorVehiculoRepository = $personaPorVehiculoRepo;
    }

    /**
     * Display a listing of the Persona_por_Vehiculo.
     *
     * @param Persona_por_VehiculoDataTable $personaPorVehiculoDataTable
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(Persona_por_VehiculoDataTable $personaPorVehiculoDataTable)
    {
        return $personaPorVehiculoDataTable->render('persona_por__vehiculos.index');
    }

    /**
     * Show the form for creating a new Persona_por_Vehiculo.
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function create()
    {
        return view('persona_por__vehiculos.create');
    }

    /**
     * Store a newly created Persona_por_Vehiculo in storage.
     *
     * @param CreatePersona_por_VehiculoRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function store(CreatePersona_por_VehiculoRequest $request)
    {
        $input = $request->all();

        $personaPorVehiculo = $this->personaPorVehiculoRepository->create($input);

        Flash::success('Persona Por  Vehiculo saved successfully.');

        return redirect(route('personaPorVehiculos.index'));
    }

    /**
     * Display the specified Persona_por_Vehiculo.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function show($id)
    {
        $personaPorVehiculo = $this->personaPorVehiculoRepository->find($id);

        if (empty($personaPorVehiculo)) {
            Flash::error('Persona Por  Vehiculo not found');

            return redirect(route('personaPorVehiculos.index'));
        }

        return view('persona_por__vehiculos.show')->with('personaPorVehiculo', $personaPorVehiculo);
    }

    /**
     * Show the form for editing the specified Persona_por_Vehiculo.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function edit($id)
    {
        $personaPorVehiculo = $this->personaPorVehiculoRepository->find($id);

        if (empty($personaPorVehiculo)) {
            Flash::error('Persona Por  Vehiculo not found');

            return redirect(route('personaPorVehiculos.index'));
        }

        return view('persona_por__vehiculos.edit')->with('personaPorVehiculo', $personaPorVehiculo);
    }

    /**
     * Update the specified Persona_por_Vehiculo in storage.
     *
     * @param  int              $id
     * @param UpdatePersona_por_VehiculoRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function update($id, UpdatePersona_por_VehiculoRequest $request)
    {
        $personaPorVehiculo = $this->personaPorVehiculoRepository->find($id);

        if (empty($personaPorVehiculo)) {
            Flash::error('Persona Por  Vehiculo not found');

            return redirect(route('personaPorVehiculos.index'));
        }

        $personaPorVehiculo = $this->personaPorVehiculoRepository->update($request->all(), $id);

        Flash::success('Persona Por  Vehiculo updated successfully.');

        return redirect(route('personaPorVehiculos.index'));
    }

    /**
     * Remove the specified Persona_por_Vehiculo from storage.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function destroy($id)
    {
        $personaPorVehiculo = $this->personaPorVehiculoRepository->find($id);

        if (empty($personaPorVehiculo)) {
            Flash::error('Persona Por  Vehiculo not found');

            return redirect(route('personaPorVehiculos.index'));
        }

        $this->personaPorVehiculoRepository->delete($id);

        Flash::success('Persona Por  Vehiculo deleted successfully.');

        return redirect(route('personaPorVehiculos.index'));
    }
}

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Persona Por  Vehiculo
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'personaPorVehiculos.store']) !!}

                        @include('persona_por__vehiculos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/datatables_actions.blade.php
{!! Form::open(['route' => ['personaPorVehiculos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('personaPorVehiculos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('personaPorVehiculos.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Persona Por  Vehiculo
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($personaPorVehiculo, ['route' => ['personaPorVehiculos.update', $personaPorVehiculo->id], 'method' => 'patch']) !!}

                        @include('persona_por__vehiculos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/fields.blade.php
<!-- Vehiculos Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vehiculos_id', 'Vehiculos Id:') !!}
    {!! Form::number('vehiculos_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Personas Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('personas_id', 'Personas Id:') !!}
    {!! Form::number('personas_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('personaPorVehiculos.index') }}" class="btn btn-default">Cancel</a>
</div>

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Persona Por  Vehiculos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('personaPorVehiculos.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('persona_por__vehiculos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Persona Por  Vehiculo
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('persona_por__vehiculos.show_fields')
                    <a href="{{ route('personaPorVehiculos.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/show_fields.blade.php
<!-- Vehiculos Id Field -->
<div class="form-group">
    {!! Form::label('vehiculos_id', 'Vehiculos Id:') !!}
    <p>{{ $personaPorVehiculo->vehiculos_id }}</p>
</div>

<!-- Personas Id Field -->
<div class="form-group">
    {!! Form::label('personas_id', 'Personas Id:') !!}
    <p>{{ $personaPorVehiculo->personas_id }}</p>
</div>

Laravel-proyect/laravel/resources/views/persona_por__vehiculos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush