Laravel-proyect/laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');


Route::resource('users', 'UserController');


Route::resource('personas', 'PersonaController');

Route::resource('rols', 'RolController');

Route::resource('ciudads', 'CiudadController');

Route::resource('vehiculos', 'VehiculoController');

Route::resource('personaPorVehiculos', 'Persona_por_VehiculoController');

Route::resource('marcas', 'MarcaController');

Laravel-proyect/laravel/resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

Laravel-proyect/laravel/resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ URL::asset('vendor/datatables/buttons.server-side.js') }}"></script>

Laravel-proyect/laravel/resources/views/layouts/menu.blade.php
<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{{ route('users.index') }}"><i class="fa fa-edit"></i><span>Usuarios</span></a>
</li><li class="{{ Request::is('personas*') ? 'active' : '' }}">
    <a href="{{ route('personas.index') }}"><i class="fa fa-edit"></i><span>Personas</span></a>
</li>

<li class="{{ Request::is('rols*') ? 'active' : '' }}">
    <a href="{{ route('rols.index') }}"><i class="fa fa-edit"></i><span>Rols</span></a>
</li>

<li class="{{ Request::is('ciudads*') ? 'active' : '' }}">
    <a href="{{ route('ciudads.index') }}"><i class="fa fa-edit"></i><span>Ciudads</span></a>
</li>

<li class="{{ Request::is('vehiculos*') ? 'active' : '' }}">
    <a href="{{ route('vehiculos.index') }}"><i class="fa fa-edit"></i><span>Vehiculos</span></a>
</li>

<li class="{{ Request::is('personaPorVehiculos*') ? 'active' : '' }}">
    <a href="{{ route('personaPorVehiculos.index') }}"><i class="fa fa-edit"></i><span>Persona Por  Vehiculos</span></a>
</li>

<li class="{{ Request::is('marcas*') ? 'active' : '' }}">
    <a href="{{ route('marcas.index') }}"><i class="fa fa-edit"></i><span>Marcas</span></a>
</li>